### ISSUE TITLE
你好，请问你这个是java开发的吗？

### ISSUE THREAD

**Issue by ShenGunNiTian** [yhsj0919/KMusic#1]

**Comment by yhsj0919** [comment]
@ShenGunNiTian  Kotlin开发的,兼容java,只是没对java进行特别的优化

**Comment by yhsj0919** [comment]
@ShenGunNiTian 在代码中java目录下,写了简单的调用,有时间可以去看下

**Comment by ShenGunNiTian** [comment]
请问是java web的还是android的？

**Comment by yhsj0919** [comment]
@ShenGunNiTian 都支持，有一个安卓音乐demo，用了这个，你可以在我的库里看一下

**Comment by ShenGunNiTian** [comment]
好的，谢谢了，我是想搞一个类似这样的（http://music.heiya123.com），再增加一些东西，完善一下

**Comment by yhsj0919** [comment]
@ShenGunNiTian 可以,
但是,
切勿用作商业用途
切勿用作商业用途
切勿用作商业用途
也可参考大神php版本 https://github.com/maicong/music ,支持的网站更多
那几个原创音乐,我没实现,没那种听歌需求

**Comment by ShenGunNiTian** [comment]
商业用途到不会，只是想搞一个自己的音乐网站，因为自己也是学开发的

**Comment by ShenGunNiTian** [comment]
基本可以实现了，只是想把播放条那里的歌曲名和时间等等加上去，以及播放列表中可以删除单条歌曲

**Comment by yhsj0919** [comment]
@ShenGunNiTian  如果还有什么需求或者问题,欢迎Issuse,不定期更新
