### ISSUE TITLE
你好，这个https://github.com/Hxiaodou/heiyaMusic和http://music.heiya123.com怎么把播放条的时间和歌手歌名加上去

### ISSUE THREAD

**Issue by ShenGunNiTian** [yhsj0919/KMusic#3]

**Comment by yhsj0919** [comment]
播放条你自己看一下你使用的播放器的回调吧,应该有关于时间的回调,我的api里不包含歌曲时间,至于歌名和歌手,我返回的信息里都包含了,播放的时候在想展示的地方赋一下值就好了

**Comment by ShenGunNiTian** [comment]
你的api是哪个文件呢，还有js返回歌曲数据内容是哪一个，不好意思了。。。

**Comment by yhsj0919** [comment]
应该是你自己建的服务器吧,我的只写了统一的搜索接口,KMusic.kt   调用这个就好了,或者看一下Main文件的测试,
